"""empty message

Revision ID: 0fdcc8356281
Revises: 
Create Date: 2023-07-12 15:32:58.460329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fdcc8356281'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional', schema=None) as batch_op:
        batch_op.drop_constraint('additional_comp_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'components', ['comp_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('amounts', schema=None) as batch_op:
        batch_op.drop_constraint('amounts_comp_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'components', ['comp_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_info_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('components_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'public_info', ['public_info_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('date')
        batch_op.drop_column('title')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_constraint('links_comp_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'components', ['comp_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_constraint('prices_comp_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'components', ['comp_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('public_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('total_price',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('public_info_comp_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('comp_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comp_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('public_info_comp_id_fkey', 'components', ['comp_id'], ['id'])
        batch_op.alter_column('total_price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('user_id')
        batch_op.drop_column('title')
        batch_op.drop_column('date')

    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('prices_comp_id_fkey', 'components', ['comp_id'], ['id'])

    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('links_comp_id_fkey', 'components', ['comp_id'], ['id'])

    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('components_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('public_info_id')

    with op.batch_alter_table('amounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('amounts_comp_id_fkey', 'components', ['comp_id'], ['id'])

    with op.batch_alter_table('additional', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('additional_comp_id_fkey', 'components', ['comp_id'], ['id'])

    # ### end Alembic commands ###
