"""empty message

Revision ID: 543385198a18
Revises: 6d8c4897d94e
Create Date: 2023-07-13 14:11:42.521950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543385198a18'
down_revision = '6d8c4897d94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
