"""empty message

Revision ID: 6d8c4897d94e
Revises: 0fdcc8356281
Create Date: 2023-07-12 15:41:10.451241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8c4897d94e'
down_revision = '0fdcc8356281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional', schema=None) as batch_op:
        batch_op.drop_constraint('additional_comp_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'components', ['comp_id'], ['id'])

    with op.batch_alter_table('amounts', schema=None) as batch_op:
        batch_op.drop_constraint('amounts_comp_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'components', ['comp_id'], ['id'])

    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_constraint('components_public_info_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'public_info', ['public_info_id'], ['id'])

    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_constraint('links_comp_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'components', ['comp_id'], ['id'])

    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_constraint('prices_comp_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'components', ['comp_id'], ['id'])

    with op.batch_alter_table('public_info', schema=None) as batch_op:
        batch_op.drop_constraint('public_info_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('public_info_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('prices_comp_id_fkey', 'components', ['comp_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('links_comp_id_fkey', 'components', ['comp_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('components_public_info_id_fkey', 'public_info', ['public_info_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('amounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('amounts_comp_id_fkey', 'components', ['comp_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('additional', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('additional_comp_id_fkey', 'components', ['comp_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
