"""empty message

Revision ID: c45c9bf20080
Revises: 5ec02ca86014
Create Date: 2023-06-30 18:08:19.815800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45c9bf20080'
down_revision = '5ec02ca86014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('psu', sa.Integer(), nullable=True))
        batch_op.drop_column('power_supply')

    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('psu', sa.String(length=255), nullable=True))
        batch_op.drop_column('power_supply')

    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('psu', sa.Integer(), nullable=True))
        batch_op.drop_column('power_supply')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('power_supply', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('psu')

    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('power_supply', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('psu')

    with op.batch_alter_table('amounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('power_supply', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('psu')

    # ### end Alembic commands ###
