"""empty message

Revision ID: fb9db1db3e61
Revises: 63d3e8a7c214
Create Date: 2023-07-05 17:50:40.207344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9db1db3e61'
down_revision = '63d3e8a7c214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
